name: Post Weekly Quest

on:
  schedule:
    - cron: '0 7 * * FRI'    # Freitags um 07:00 UTC (=09:00 MEZ)
  workflow_dispatch:         # erlaubt manuellen Trigger

jobs:
  post-quest:
    runs-on: ubuntu-latest
    steps:
      - name: Call Quest Endpoint
        env:
          API_KEY: ${{ secrets.INSTANTBOT_API_KEY }}
        run: |
          curl -X POST https://development--questautomator--nudel2577.instant.host/postWeeklyQuest \
               -H "Content-Type: application/json" \
               -H "Authorization: $API_KEY"
