name: Post Weekly Quest

on:
  schedule:
    - cron: '0 7 * * FRI'
  workflow_dispatch:

jobs:
  post-quest:
    runs-on: ubuntu-latest
    steps:
      - name: Call Quest Endpoint
        run: |
          curl -X POST https://development--questautomator--nudel2577.instant.host/postWeeklyQuest \
               -H "Content-Type: application/json" \
               -H "Authorization: Bearer keychain_secret_Y5bWqnqiABFDsGYTEwV7DQuVWbTDsBUG1nH6DEkXx6WaSeuXrxoDXa1dQx3Tkx5Y"
