name: Post Weekly Quest

on:
  schedule:
    - cron: '0 7 * * FRI'    # Freitags um 07:00 UTC (=09:00 MEZ)
  workflow_dispatch:         # erlaubt manuellen Trigger

jobs:
  post-quest:
    runs-on: ubuntu-latest
    steps:
      - name: Call Quest Endpoint (v-20250618) # Namen des Schrittes angepasst
        run: |
          curl -X POST https://v-20250618--questautomator--nudel2577.instant.host/postWeeklyQuest \
               -H "Content-Type: application/json" \
               -H "Authorization: Bearer ${{ secrets.INSTANTBOT_API_KEY }}"
